// Generated by CoffeeScript 1.6.2
var Aggr, HttpMock, assert, httpMock, should;

assert = require('assert');

HttpMock = require('./mocks/httpMock');

Aggr = require('./../lib/aggr');

should = require('should');

httpMock = new HttpMock();

describe('Aggr', function() {
  return it('single request', function(done) {
    var aggr, data, url;

    url = '/parent/:parentId';
    data = {
      name: 'parent'
    };
    httpMock.expectGET('/parent/1', data, 200);
    aggr = new Aggr(httpMock);
    return aggr.request(url, {
      parentId: 1
    }).exec(function(error, result) {
      result.should.have.property('status', 200);
      result.data.should.have.property('name', data.name);
      return done();
    });
  });
});
