// Generated by CoffeeScript 1.4.0
var HttpMock, assert, httpMock;

assert = require('assert');

HttpMock = require('./mocks/httpMock');

httpMock = new HttpMock();

describe('Aggr', function() {
  return it('simple request', function(done) {
    var aggr, data, url;
    url = '/parent/:parentId';
    data = {
      name: 'parent'
    };
    httpMock.expectGET(url, data, 200);
    aggr = new Aggr(httpMock);
    return aggr.request(url, {
      parentId: 1
    }).exec(function(error, result) {
      return console.log(result);
    });
  });
});
