// Generated by CoffeeScript 1.4.0
var Aggr, Request, async, exports, superagent;

superagent = require('superagent');

async = require('async');

Request = (function() {

  function Request(urlTemplate, urlParams) {
    this.urlTemplate = urlTemplate;
    this.urlParams = urlParams;
  }

  Request.prototype.parseUrl = function() {
    var urlParam, value, _ref, _results;
    this.url = this.urlTemplate.toLowerCase();
    _ref = this.urlParams;
    _results = [];
    for (urlParam in _ref) {
      value = _ref[urlParam];
      _results.push(this.url = this.url.replace(':' + urlParam.toLowerCase(), value));
    }
    return _results;
  };

  return Request;

})();

Aggr = (function() {

  Aggr.prototype.urlTemplates = [];

  function Aggr(http) {
    this.http = http != null ? http : new superagent.agent();
  }

  Aggr.prototype.request = function(urlTemplate, urlParam) {
    if (typeof ulrParam === 'object') {
      urlParam = {
        id: urlParam
      };
    }
    this.urlTemplate.push(new Request(urlTemplate, urlParam));
    return this;
  };

  return Aggr;

})();

Aggr.Request = Request;

exports = module.exports = Aggr;
